version: '3.8'

services:
  bytetrack:
    build: ./
    devices:
      - /dev/video0:/dev/video0
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - NVIDIA_VISIBLE_DEVICES=nvidia.com/gpu=all
    volumes:
      - .:/root/ros2_ws/src
      - /dev/dri:/dev/dri
    runtime: nvidia
    privileged: true
    tty: true
    stdin_open: true
    network_mode: host
    ipc: host
    command: tail -f /dev/null