version: '3.8'

services:
  bytetrack:
    build: ./
    devices:
      - /dev/video0:/dev/video0
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - NVIDIA_VISIBLE_DEVICES=nvidia.com/gpu=all
      - CYCLONEDDS_URI=file:///root/ros2_ws/src/config_file.xml
    volumes:
      - .:/root/ros2_ws/src
      - /dev/dri:/dev/dri
    runtime: nvidia
    privileged: true
    tty: true
    stdin_open: true
    network_mode: host
    ipc: host
    command: tail -f /dev/null

    #TO BE REMOVED LATER ON.
    #command: /bin/bash -c "source install/setup.bash && ros2 launch yolo_bringup yolo.launch.py tracker:=/root/ros2_ws/src/config/bytetrack.yaml input_image_topic:=/image_raw/compressed image_reliability:=2 model:=/root/ros2_ws/src/yolo11n-seg.pt is_compressed:=True use_debug:=False threshold:=0.8"

    #ros2 run image_publisher image_publisher_node /dev/video0 --ros-args -p publisher_rate:=40.0 -p qos_overrides./image_raw/compressed.publisher.depth:=1 -p qos_overrides./image_raw/compressed.publisher.reliability:=best_effort
